version: 3

services:
  web:
    container_name: ejemplonode
    restart: always
    build: .
    ports: 
      -"5000:9000"
    links: 
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      -"27018:27017"
