###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre":"Andresito",
    "edad":23,
    "correo":"andres@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63ad30efaa8e48e32c193e40 HTTP/1.1

###
DELETE http://localhost:9000/api/users/63ab879cc7a11d890c2bae59 HTTP/1.1

###
PUT http://localhost:9000/api/users/63ad30efaa8e48e32c193e40 HTTP/1.1
Content-Type: application/json

{
  "nombre": "John Conway",
  "edad": 80,
  "correo": "johnconway@email.com"
}
